global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: 'https://webhook.site/2febce9a-6cb8-4a4c-8bb3-db655cda6442'
        send_resolved: false
